# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Durbin
email: alexanderdurbin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Learning to code in HTML, CSS, C# to make a career switch.  I'm a private tutor and damn good at what I do.  I am highly motivated and very quick to learn new things. This is the next step.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: almostincognito
github_username:  alexanderdurbin

# Build settings
markdown: kramdown
